apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
     containers:
      - name: python
        image: mmmahon64/java:0.0.3.RELEASE
        ports:
        - containerPort: 5000