apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-storage-pv # MARK Z
   namespace: website
#   labels:
#    type: local
spec:
  storageClassName: mysql
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"