apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
   name: mysql-storage-claim # MARK Z
   namespace: website
spec:
 storageClassName: mysql
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1G