apiVersion: v1
kind: Service
metadata:
  name: mysql-service # MARK B
  namespace: website # Match with namespace
spec:
  type: ClusterIP
  ports:
  - port: 3306 # MARK B.1
    targetPort: 3306 # Must match with containerPort
    protocol: TCP
  selector:
    app: mysql # Must match with `MARK A` in mysql/deployment.yaml