apiVersion: v1
kind: PersistentVolume
metadata:
   name: wordpress-storage-pv # MARK Z
   namespace: website
#   labels:
#    type: local
spec:
  storageClassName: wordpress
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"