apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
   name: wordpress-storage-claim # MARK Z
   namespace: website
spec:
 storageClassName: wordpress
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1G