apiVersion: v1
kind: Service
metadata:  
  name: nginx-cluster
  labels:
    app: nginx
spec:
  selector:    
    app: nginx
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
   # protocol: